version: "3.1"
services: 
  # python:
  #   # docker run --name module_project
  #   container_name: module_project
  #   # FROM python:3.7
  #   image: python:3.7
  #   # docker run -v ./:/root/module_project
  #   volumes: "./:/root/module_project"
  #   # WORKDIR /root/module_project
  #   working_dir: /root/module_project
  #   # CMD ["python", "main.py"]
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   # command: ./run.sh
  #   command: python main.py

  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: /run.sh
    # volumes:
    #   - "./:/root/module_project"
    command:
      tail -f /dev/null
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes: 
      - ./datadir:/var/lib/mysql