version: '3.1'

services:
    python:
        container_name: python
        build:
            context: .
            dockerfile: ./Dockerfile
        # volumes: 
        #     - ./:/root/module_project
        depends_on: 
            - mysql
        command: tail -f /dev/null

    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes: 
            - ./db_data:/root/module_project/db_data
            # docker의 db구조에서 약속된 형태로 여기에 넣은 sql이나 sh는 시작하자마자 구동한다.
            - ./mysql_init_files/:/docker-entrypoint-initdb.d/
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD="true"
        ports: 
            - "3306:3306"