version: '3.1'

services:
    python:
        container_name: python
        build:
            context: .
            dockerfile: ./Dockerfile
        # volumes: 
        #     - ./:/root/module_project
        # python 실행 컨테이너가 종료되지 않고 유지
        command: tail -f /dev/null
        # mysql 컨테이너가 있어야만 python 서비스가 작동된다
        depends_on: 
            - mysql

    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        # volumes:
            # docker의 db구조에서 약속된 형태로 여기에 넣은 sql이나 sh는 시작하자마자 구동한다.
            # - ./mysql_init_files/:/docker-entrypoint-initdb.d/
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD="true"
        ports: 
            - "3306:3306"